-- vim.api.nvim_create_autocmd("FileType", {
--   pattern = "zig",
--   callback = function()
--     local bufnr = vim.api.nvim_get_current_buf()
-- 
--     -- Start LSP if not already running
--     local clients = vim.lsp.get_active_clients({ bufnr = bufnr })
--     local running = false
--     for _, client in ipairs(clients) do
--       if client.name == "zls" then
--         running = true
--         break
--       end
--     end
-- 
--     if not running then
--       vim.lsp.start({
--         name = "zls",
--         cmd = { "zls" },
--         root_dir = vim.fn.getcwd(),
--         filetypes = { "zig" },
--       })
--     end
-- 
--   end,
-- })
-- 
