modmap:
  # Remap CapsLock to Left Control key
  - name: Global
    remap:
      CapsLock: Ctrl_L
keymap:
  # Arrow keys for pok3r keyboard
  - name: Arrow Keys
    remap:
      Alt-w: up
      Alt-s: down
      Alt-a: left
      Alt-d: right
  - name: Tilde
    remap:
      Alt-Esc: grave
      Alt-Shift_R-Esc: shift-grave
