#!/usr/bin/env bash


# model and Serial numbers:
VECNA_LEFT="CPBQFZ2"
VECNA_RIGHT="9K9QFZ2"

HOME_LEFT="JM422H3"
HOME_RIGHT="DT2J9H3"

# Get outputs in the format: "eDP-1: Sharp Corporation", "DP-1: Dell Inc.", etc.
outputs_json=$(swaymsg -t get_outputs)
echo "$outputs"

has_external_monitors() {
    local serial=$1
    if echo "$outputs_json" | jq -e --arg serial "$serial" \
            '.[] | select(.active == true and .serial == $serial)'; then
        return 0 #true
    else
        return 1 #false
    fi
}

position_monitors() {
    local left_monitor="$1"
    local right_monitor="$2"

    swaymsg output eDP-1 disable

    swaymsg output "$left_monitor" resolution 1920x1080 position 0 0 enable
    swaymsg workspace "$LEFT_WS1" output "$left_monitor" 
    swaymsg workspace "$LEFT_WS2" output "$left_monitor" 

    swaymsg output "$right_monitor" resolution 1920x1080 position 1920 0 enable
    swaymsg workspace "$RIGHT_WS1" output "$right_monitor"
    swaymsg workspace "$RIGHT_WS2" output "$right_monitor"
}

if has_external_monitors $VECNA_LEFT; then
    echo "Vecna Office monitors detected"
    lm=$(echo "$outputs_json" | jq -r --arg serial "$VECNA_LEFT" \
            '.[] | select(.serial == $serial) | .name')
    rm=$(echo "$outputs_json" | jq -r --arg serial "$VECNA_RIGHT" \
            '.[] | select(.serial == $serial) | .name')
    position_monitors "$lm" "$rm"
elif has_external_monitors $HOME_LEFT; then
    echo "Home Office monitors detected"
    lm=$(echo "$outputs_json" | jq -r --arg serial "$HOME_LEFT" \
            '.[] | select(.serial == $serial) | .name')
    rm=$(echo "$outputs_json" | jq -r --arg serial "$HOME_RIGHT" \
            '.[] | select(.serial == $serial) | .name')
    position_monitors "$lm" "$rm"
else
    echo "No external monitors"
    swaymsg output eDP-1 enable
fi
