#!/usr/bin/env bash
# Watch for keyboards, and bind xremap to them
# Not explicitly binding keyboard. could be done using --device /dev/input/event2
# but its complex to includ native and external keyboards

exec /usr/bin/xremap /home/gevious/.config/xremap/config.yml --watch
