#!/usr/bin/env bash
# Inspired by ThePrimeagen's scripts

# Shows all top-level directories in BASE_DIR, except DIRECTORIES
# all DIRECTORIES show up along with 1 additional child directory

BASE_DIR="${HOME}/w"
CATEGORIES="groundskeeper vecna"

entries=$(
  for dir in "$BASE_DIR"/*; do
    [ -d "$dir" ] || continue
    name="${dir#$BASE_DIR/}"

    if [[ " $CATEGORIES " == *" $name "* ]]; then
      # Print subdirectories of the matching directory
      find "$dir" -mindepth 1 -maxdepth 1 -type d | while read -r sub; do
        echo "${sub#$BASE_DIR/}"
      done
    else
      # Print the directory itself
      echo "$name"
    fi
  done
)

selected_name=$(while IFS= read -r entry; do
  echo "$entry"
done <<< "$entries" | fzf) 

if [[ -z $selected_name ]]; then
    exit 0
fi

selected="$BASE_DIR/$selected_name"
echo "Selected: $selected"
echo "Selectedname: $selected_name"
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
